### ISSUE TITLE
about image and audio feature extraction

### ISSUE THREAD

**Issue by cm-xcju** [NUSTM/MECPE#1]
I'm interested in your datasets. But when I read the code, I find you have provided a processed visual and acoustic feature. Can you provide me with the  processing code for video and audio?

**Comment by ffcarina** [comment]
Sorry, we haven't reserved the processing code for video and audio. However, this part is easy to reproduce.  We obtained the representation of the last layer of the C3D model as the visual features based on the code from this repository: https://github.com/jfzhang95/pytorch-video-recognition. To extract the acoustic features, you can install the openSMILE toolkit and use the following command line: 
```
opensmile/build/progsrc/smilextract/SMILExtract -C opensmile/config/is09-13/IS09_emotion.conf -I input.wav -O output.txt
```

**Comment by ffcarina** [comment]
@cm-xcju  Sorry, we haven't reserved the processing code for video and audio. However, this part is easy to reproduce.  We obtained the representation of the last layer of the C3D model as the visual features based on the code from this repository: https://github.com/jfzhang95/pytorch-video-recognition. To extract the acoustic features, you can install the openSMILE toolkit and use the following command: 
```
opensmile/build/progsrc/smilextract/SMILExtract -C opensmile/config/is09-13/IS09_emotion.conf -I input.wav -O output.txt
```
