### ISSUE TITLE
video_embedding_4096.npy

### ISSUE THREAD

**Issue by 277CPS** [NUSTM/MECPE#2]
cannot reshape array of size 3276784 into shape (13620,4096)

**Comment by ffcarina** [comment]
Have you loaded this file in the correct way? Please refer to this line of code: https://github.com/NUSTM/MECPE/blob/9fbe4d9ca1e55adb91baa8ffd0f39194a7fa5224/utils/pre_data_bert.py#L106C5-L106C5

**Comment by ffcarina** [comment]
@277CPS  Have you loaded this file in the correct way? Please refer to this line of code: https://github.com/NUSTM/MECPE/blob/9fbe4d9ca1e55adb91baa8ffd0f39194a7fa5224/utils/pre_data_bert.py#L106C5-L106C5

**Comment by 277CPS** [comment]
Thanks,the problem has been solved
