### ISSUE TITLE
About the Extraction of Audio Embeddings

### ISSUE THREAD

**Issue by W-ZN** [NUSTM/MECPE#3]
```bash
ffmpeg -i video -ab 160k -ac 2 -ar 44100 -vn input.wav

opensmile/build/progsrc/smilextract/SMILExtract -C opensmile/config/is09-13/IS09_emotion.conf -I input.wav -O output.txt
```
I used the above command to process video files and extract audio features using the IS09 feature set of opensmile. However, there is a significant difference in dimensionality compared to the 6373 dimensions used in the experiment. Could you please provide more details on this part? How were the 6373-dimensional features extracted from the video? 

Thank you very much!

**Comment by ffcarina** [comment]
@W-ZN   Sorry, I made a mistake. The feature set reported in the paper is incorrect. In fact, I ended up using the `IS13_ComParE` feature set.
```
ffmpeg  -i input.mp4  -f wav -ac 2 -vn -map 0:1 output.wav

opensmile/build/progsrc/smilextract/SMILExtract -C opensmile/config/is09-13/IS13_ComParE.conf -I input.wav -O output.txt
```

**Comment by W-ZN** [comment]
> @W-ZN Sorry, I made a mistake. The feature set reported in the paper is incorrect. In fact, I ended up using the `IS13_ComParE` feature set.
> 
> ```
> ffmpeg  -i input.mp4  -f wav -ac 2 -vn -map 0:1 output.wav
> 
> opensmile/build/progsrc/smilextract/SMILExtract -C opensmile/config/is09-13/IS13_ComParE.conf -I input.wav -O output.txt
> ```

Thank for your reply! I will use this method for processing!
