### ISSUE TITLE
21世纪了，来点现代框架吧

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [NUSTM/MECPE#7]
能给个pytorch实现吗，tensorflow静态图很难调试

**Comment by ffcarina** [comment]
@qwertyuiopasdfghjklzxcn 
Thank you for your attention to our work. 
There is already the [PyTorch implementation for the ECPE task](https://github.com/bbruceyuan/ECPE-PyTorch), which you can modify accordingly. Sorry for the inconvenience. Our dataset has been fully released, and we welcome you to explore more advanced and effective methods.
